import { apiClient } from './apiClient'

export type AnalyticsRange = 'week' | 'month' | 'year'

export interface AnalyticsKpi {
  views: number
  messages: number
  bookings: number
  reviews: number
  avgRating: number
}

export interface AnalyticsChart {
  data: number[]
  buckets: number
  range: AnalyticsRange
}

export interface AnalyticsService {
  id: number
  publicId?: string
  title: string
  views: number
  messages: number
  bookings: number
  reviewsCount: number
  avgRating: number
}

export interface AnalyticsResponse {
  kpi: AnalyticsKpi
  chart: AnalyticsChart
  services: AnalyticsService[]
}

export interface ApiReview {
  id: number
  serviceId: number
  serviceTitle: string
  rating: number
  text: string | null
  date: string
  dateLabel: string
  userName: string
  userAvatar: string | null
  userUid: string
  autoGenerated: boolean
  isNew: boolean
  ownerReply: string | null
}

export interface ReviewsMeta {
  total: number
  page: number
  limit: number
  pages: number
  average: number
  new30d: number
  recommendedPct: number
}

export interface ReviewsResponse {
  data: ApiReview[]
  meta: ReviewsMeta
}

export interface EarningsKpi {
  earnedPeriod: number
  pending: number
  totalEarned: number
  completedCount: number
}

export interface EarningsTransaction {
  id: number
  serviceId: number
  servicePublicId?: string
  serviceTitle: string
  amount: number
  priceUnit: string
  clientName: string
  clientAvatar: string | null
  status: string
  date: string
  dateLabel: string
}

export interface EarningsResponse {
  kpi: EarningsKpi
  chart: AnalyticsChart
  transactions: EarningsTransaction[]
}

export async function getMyEarnings(range: AnalyticsRange = 'month'): Promise<EarningsResponse> {
  const res = await apiClient(`/users/me/earnings?range=${range}`)
  if (!res.ok) throw new Error('Failed to fetch earnings')
  return res.json()
}

export async function getMyAnalytics(range: AnalyticsRange = 'month'): Promise<AnalyticsResponse> {
  const res = await apiClient(`/users/me/analytics?range=${range}`)
  if (!res.ok) throw new Error('Failed to fetch analytics')
  return res.json()
}

export interface ManualIncomeEntry {
  id: number
  date: string
  description: string
  amount: number
  buyerName: string | null
  createdAt: string
}

export interface YearlyBreakdownItem {
  month: number
  income: number
}

export interface UnregisteredActivityData {
  enabled: boolean
  monthlyLimit: number
  currentMonthIncome: number
  currentMonthPercent: number
  ytdIncome: number
  warningLevel: 'ok' | 'warning' | 'danger'
  userData: { fullName: string; addressStreet: string; addressCity: string; addressPostal: string }
  transactions: EarningsTransaction[]
  manualEntries: ManualIncomeEntry[]
  yearlyBreakdown: YearlyBreakdownItem[]
}

export interface IncomeReportRow {
  lp?: number
  date: string
  description: string
  buyerName: string | null
  amount: number
  source: 'platform' | 'manual'
}

export interface IncomeReportData {
  monthlyLimit: number
  totalAmount: number
  userData: { fullName: string; addressStreet: string; addressCity: string; addressPostal: string }
  transactions: IncomeReportRow[]
  manualEntries: IncomeReportRow[]
}

export async function getUnregisteredActivity(year?: number, month?: number): Promise<UnregisteredActivityData> {
  const qs = new URLSearchParams()
  if (year) qs.set('year', String(year))
  if (month) qs.set('month', String(month))
  const res = await apiClient(`/users/me/unregistered-activity?${qs.toString()}`)
  if (!res.ok) throw new Error('Failed to fetch unregistered activity')
  return res.json()
}

export async function addManualIncome(entry: { date: string; description: string; amount: number; buyerName?: string }): Promise<ManualIncomeEntry> {
  const res = await apiClient.post('/users/me/manual-income', entry as unknown as Record<string, unknown>)
  if (!res.ok) throw new Error('Failed to add manual income')
  return res.json()
}

export async function deleteManualIncome(id: number): Promise<void> {
  const res = await apiClient.delete(`/users/me/manual-income/${id}`)
  if (!res.ok) throw new Error('Failed to delete manual income entry')
}

export async function getManualIncomeList(): Promise<ManualIncomeEntry[]> {
  const res = await apiClient('/users/me/manual-income')
  if (!res.ok) throw new Error('Failed to fetch manual income list')
  return res.json()
}

export async function getIncomeReport(startDate: string, endDate: string): Promise<IncomeReportData> {
  const res = await apiClient(`/users/me/income-report?startDate=${startDate}&endDate=${endDate}`)
  if (!res.ok) throw new Error('Failed to fetch income report')
  return res.json()
}

export async function getMyReviews(params?: {
  sort?: 'newest' | 'highest' | 'lowest'
  page?: number
  limit?: number
}): Promise<ReviewsResponse> {
  const qs = new URLSearchParams()
  if (params?.sort) qs.set('sort', params.sort)
  if (params?.page) qs.set('page', String(params.page))
  if (params?.limit) qs.set('limit', String(params.limit))
  const res = await apiClient(`/users/me/reviews?${qs.toString()}`)
  if (!res.ok) throw new Error('Failed to fetch reviews')
  return res.json()
}
