'use client';
import { lockScroll, unlockScroll } from '../../../utils/scrollLock';
import { useState, useEffect, lazy, Suspense, useRef, useMemo, type ReactNode } from 'react';
import { apiClient } from '../../../services/apiClient';
import { motion, AnimatePresence } from 'framer-motion';
import { ArrowLeft, Star, MessageSquare, ChevronDown, ArrowRight } from 'lucide-react';
import { ReviewSidebar } from './ReviewSidebar';
import { useSwipeBack } from '../../../hooks/useSwipeBack';
import { useQuery } from '@tanstack/react-query';
import { getMyReviews, type ApiReview } from '../../../services/analyticsService';
import { UserAvatar } from '../../../components/ui/UserAvatar';
const ReportModal = lazy(() => import('../../../components/modals/ReportModal').then(m => ({ default: m.ReportModal })));

const REVIEWS_SEEN_KEY = 'reviews_last_seen_at';
function getLastSeenAt(): number {
    return parseInt(localStorage.getItem(REVIEWS_SEEN_KEY) ?? '0', 10);
}

export const ReviewsDetail = ({ onBack }: { onBack: () => void }) => {
    const [selectedReview, setSelectedReview] = useState<ApiReview | null>(null);
    const [visibleLimit, setVisibleLimit] = useState(5);
    const [pageSize, setPageSize] = useState(5);
    const [lastSeenAt, setLastSeenAt] = useState<number>(() => getLastSeenAt());

    const [isReportOpen, setIsReportOpen] = useState(false);
    const [reportType, setReportType] = useState<'review' | 'profile'>('review');
    const reportTargetRef = useRef<{ type: string; id: string } | null>(null);

    useSwipeBack(!selectedReview && !isReportOpen, onBack);

    const { data, isLoading } = useQuery({
        queryKey: ['my-reviews'],
        queryFn: () => getMyReviews({ limit: 50 }),
        staleTime: 60_000,
    });

    const allReviews = useMemo(() => data?.data ?? [], [data?.data]);
    const meta = data?.meta;

    // Po 1.5s widoku zapisz timestamp — znikają badge dla wszystkich aktualnie widocznych nowych opinii
    useEffect(() => {
        const hasUnseen = allReviews.some(r => r.isNew && !r.autoGenerated && new Date(r.date).getTime() > lastSeenAt);
        if (!hasUnseen) return;
        const t = setTimeout(() => {
            const now = Date.now();
            localStorage.setItem(REVIEWS_SEEN_KEY, String(now));
            setLastSeenAt(now);
        }, 1500);
        return () => clearTimeout(t);
    }, [allReviews, lastSeenAt]);

    const REASON_MAP: Record<string, string> = {
        'Spam': 'spam', 'Treści reklamowe': 'spam',
        'Fałszywe konto': 'fraud', 'Fałszywa opinia': 'fraud', 'Oszustwo': 'fraud',
        'Nękanie': 'inappropriate_content', 'Wulgaryzmy': 'inappropriate_content',
        'Nieodpowiednie treści': 'inappropriate_content', 'Niedozwolone treści': 'inappropriate_content',
        'Zła kategoria': 'other', 'Nieaktualne': 'other',
    };

    const handleOpenReport = (type: 'review' | 'profile') => {
        const id = String(selectedReview?.userUid ?? selectedReview?.id ?? '');
        reportTargetRef.current = { type: type === 'review' ? 'review' : 'user', id };
        setReportType(type);
        setIsReportOpen(true);
    };

    const handleReportSubmit = async (reason: string) => {
        const target = reportTargetRef.current;
        if (!target?.id) return;
        try {
            await apiClient.post('/reports', {
                targetType: target.type,
                targetId: target.id,
                reason: REASON_MAP[reason] ?? 'other',
            });
        } catch {
            // cicho — modal już się zamknął
        }
    };

    useEffect(() => {
        if (selectedReview) lockScroll(); else unlockScroll();
        return () => { unlockScroll(); };
    }, [selectedReview]);

    useEffect(() => {
        const calculateVisible = () => {
            const isMobile = window.innerWidth < 768;
            const rowHeight = 110;
            const offset = isMobile ? 340 : 520;
            const availableHeight = window.innerHeight - offset;
            const count = Math.max(3, Math.floor(availableHeight / rowHeight));
            setPageSize(count);
            setVisibleLimit(count);
        };
        calculateVisible();
        window.addEventListener('resize', calculateVisible);
        return () => window.removeEventListener('resize', calculateVisible);
    }, []);

    const displayedReviews = allReviews.slice(0, visibleLimit);
    const hasMore = visibleLimit < allReviews.length;
    const handleLoadMore = () => setVisibleLimit(prev => prev + pageSize);

    const avgStr = meta ? (isNaN(meta.average) || meta.average === null || meta.average === undefined ? 0 : meta.average).toFixed(1) : '0.0';
    const totalStr = meta ? String(meta.total) : '0';
    const recStr = meta ? `${meta.recommendedPct}%` : '0%';
    const newStr = meta ? (meta.new30d > 0 ? `+${meta.new30d}` : '0') : '0';

    return (
        <div className="relative">
            <motion.div
                initial={{ opacity: 0, x: 20 }}
                animate={{ opacity: 1, x: 0 }}
                exit={{ opacity: 0, x: -20 }}
                className={`space-y-6 text-left pb-24 ${selectedReview ? 'md:blur-sm pointer-events-none md:scale-[0.98] transition-all duration-500' : ''}`}
            >
                <button onClick={onBack} className="flex items-center gap-2 text-gray-500 hover:text-gray-900 transition-colors mb-4 group">
                    <div className="p-2 bg-gray-100 rounded-full group-hover:bg-gray-200 transition-colors">
                        <ArrowLeft size={18} />
                    </div>
                    <span className="font-bold text-sm">Powrót do podsumowania</span>
                </button>

                <div className="flex flex-col md:flex-row justify-between items-start md:items-end gap-4 mb-8">
                    <div>
                        <h2 className="text-3xl font-black text-gray-900 tracking-tight">Opinie</h2>
                        <p className="text-gray-500 font-medium">Zarządzaj swoją reputacją i buduj zaufanie.</p>
                    </div>
                    <div className="flex bg-indigo-50 text-[#6366F1] px-4 py-2 rounded-2xl border border-indigo-100 items-center gap-2 self-start md:self-auto shadow-sm">
                        <Star size={18} fill="currentColor" />
                        <span className="font-black text-sm">
                            {isLoading ? '...' : `${avgStr} / 5.0`}
                        </span>
                    </div>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-3 gap-3 md:gap-4">
                    <StatCard title="Wszystkich opinii" value={totalStr} icon={<MessageSquare size={16} />} isLoading={isLoading} />
                    <StatCard title="Polecenia" value={recStr} icon={<Star size={16} />} isLoading={isLoading} />
                    <StatCard title="Nowe (30 dni)" value={newStr} icon={<Star size={16} />} isMain={true} isLoading={isLoading} />
                </div>

                <div className="bg-white rounded-[2rem] border border-gray-100 shadow-sm overflow-hidden text-left">
                    <div className="px-6 py-5 border-b border-gray-50 flex items-center justify-between">
                        <h4 className="font-bold text-gray-900 text-sm">Ostatnie recenzje</h4>
                        <span className="text-[10px] font-bold text-gray-400 uppercase tracking-widest">
                            Widoczne: {displayedReviews.length} / {allReviews.length}
                        </span>
                    </div>

                    {isLoading ? (
                        <div className="divide-y divide-gray-50">
                            {[...Array(3)].map((_, i) => (
                                <div key={i} className="p-5 md:p-6 flex items-start gap-4">
                                    <div className="w-12 h-12 bg-gray-100 rounded-[1.25rem] animate-pulse shrink-0" />
                                    <div className="flex-1 space-y-2 pt-1">
                                        <div className="h-3 bg-gray-100 rounded animate-pulse w-1/3" />
                                        <div className="h-2 bg-gray-100 rounded animate-pulse w-3/4" />
                                        <div className="h-2 bg-gray-100 rounded animate-pulse w-1/2" />
                                    </div>
                                </div>
                            ))}
                        </div>
                    ) : allReviews.length === 0 ? (
                        <div className="py-12 text-center text-gray-400">
                            <Star size={32} className="mx-auto mb-2 opacity-30" />
                            <p className="text-[10px] font-black uppercase tracking-widest">Brak opinii</p>
                            <p className="text-xs text-gray-400 mt-1">Opinie pojawią się po zakończeniu rezerwacji</p>
                        </div>
                    ) : (
                        <div className="divide-y divide-gray-50">
                            <AnimatePresence initial={false}>
                                {displayedReviews.map((review, index) => (
                                    <motion.div
                                        key={review.id}
                                        initial={index >= visibleLimit - pageSize ? { height: 0, opacity: 0 } : false}
                                        animate={{ height: 'auto', opacity: 1 }}
                                        transition={{ duration: 0.4, ease: [0.23, 1, 0.32, 1] }}
                                    >
                                        <div
                                            onClick={() => !review.autoGenerated && setSelectedReview(review)}
                                            className={`p-5 md:p-6 flex items-start justify-between transition-all group ${review.autoGenerated ? 'opacity-75' : 'hover:bg-gray-50/30 cursor-pointer'}`}
                                        >
                                            <div className="flex items-start gap-3 md:gap-4">
                                                <div className={`shrink-0 ${!review.autoGenerated ? 'group-hover:scale-110 transition-all' : ''}`}>
                                                    {review.autoGenerated ? (
                                                        <div className="w-10 h-10 rounded-xl md:rounded-[1.25rem] bg-gray-100 flex items-center justify-center">
                                                            <Star size={16} className="text-gray-300" fill="currentColor" />
                                                        </div>
                                                    ) : (
                                                        <UserAvatar src={review.userAvatar} name={review.userName || '?'} size={40} className="rounded-xl md:rounded-[1.25rem]" />
                                                    )}
                                                </div>
                                                <div>
                                                    <div className="flex items-center gap-2">
                                                        <p className="font-black text-gray-900 text-xs md:text-sm">
                                                            {review.autoGenerated ? 'Automatyczna opinia' : review.userName}
                                                        </p>
                                                        {review.isNew && !review.autoGenerated && new Date(review.date).getTime() > lastSeenAt && (
                                                            <span className="text-[8px] font-black text-indigo-500 bg-indigo-50 px-1.5 py-0.5 rounded uppercase tracking-widest">Nowa</span>
                                                        )}
                                                        {review.autoGenerated && (
                                                            <span className="text-[8px] font-black text-gray-400 bg-gray-100 px-1.5 py-0.5 rounded uppercase tracking-widest">Auto</span>
                                                        )}
                                                    </div>
                                                    {review.serviceTitle && (
                                                        <p className="text-[10px] text-indigo-400 font-bold mt-0.5 truncate max-w-xs">{review.serviceTitle}</p>
                                                    )}
                                                    {!review.autoGenerated && (
                                                        <p className="text-xs text-gray-500 mt-1 line-clamp-2 max-w-xl font-medium leading-relaxed">
                                                            {review.text || <span className="italic text-gray-300">Brak komentarza</span>}
                                                        </p>
                                                    )}
                                                    <div className="flex items-center gap-4 mt-2">
                                                        <span className={`text-[9px] md:text-[10px] font-black px-1.5 py-0.5 bg-gray-100 text-gray-400 rounded uppercase tracking-tighter ${!review.autoGenerated ? 'group-hover:bg-indigo-100 group-hover:text-indigo-600 transition-colors' : ''}`}>
                                                            {review.dateLabel}
                                                        </span>
                                                        {!review.autoGenerated && (
                                                            <div className="flex items-center gap-0.5">
                                                                {[...Array(5)].map((_, i) => (
                                                                    <Star
                                                                        key={i}
                                                                        size={10}
                                                                        className={i < review.rating ? "text-amber-400" : "text-gray-200"}
                                                                        fill={i < review.rating ? "currentColor" : "none"}
                                                                    />
                                                                ))}
                                                            </div>
                                                        )}
                                                    </div>
                                                </div>
                                            </div>
                                            {!review.autoGenerated && (
                                                <div className="p-2 bg-gray-50 rounded-full text-gray-300 group-hover:text-[#6366F1] group-hover:bg-indigo-50 transition-all ml-4 self-center">
                                                    <ArrowRight size={14} />
                                                </div>
                                            )}
                                        </div>
                                    </motion.div>
                                ))}
                            </AnimatePresence>
                        </div>
                    )}

                    {hasMore && (
                        <button onClick={handleLoadMore} className="w-full py-4 bg-gray-50/50 hover:bg-gray-50 text-gray-400 hover:text-[#6366F1] transition-all flex items-center justify-center gap-2 border-t border-gray-50 group">
                            <span className="text-[10px] font-black uppercase tracking-[0.2em]">Pokaż więcej (+{pageSize})</span>
                            <ChevronDown size={14} className="group-hover:translate-y-0.5 transition-transform" />
                        </button>
                    )}
                </div>
            </motion.div>

            <AnimatePresence>
                {selectedReview && (
                    <ReviewSidebar
                        review={selectedReview}
                        onClose={() => setSelectedReview(null)}
                        onOpenReport={handleOpenReport}
                        isModalOpen={isReportOpen}
                    />
                )}
            </AnimatePresence>

            <Suspense fallback={null}>
                <ReportModal
                    isOpen={isReportOpen}
                    onClose={() => setIsReportOpen(false)}
                    type={reportType}
                    onSubmit={handleReportSubmit}
                />
            </Suspense>
        </div>
    );
};

function StatCard({ title, value, icon, trend, isMain, isLoading }: {
    title: string; value: ReactNode; icon: ReactNode; trend?: ReactNode; isMain?: boolean; isLoading?: boolean;
}) {
    return (
        <div className={`relative p-4 md:p-6 rounded-[1.5rem] md:rounded-[1.75rem] border transition-all duration-300 flex md:flex-col items-center md:items-start gap-4 md:gap-0 ${
            isMain ? 'bg-[#6366F1] border-[#6366F1] text-white shadow-lg' : 'bg-white border-gray-100 text-gray-900 shadow-sm'
        }`}>
            <div className={`p-2.5 rounded-xl shrink-0 md:mb-4 ${isMain ? 'bg-white/20' : 'bg-indigo-50 text-[#6366F1]'}`}>
                {icon}
            </div>
            <div className="flex-1 md:w-full text-left">
                <p className="text-[9px] md:text-[10px] font-bold uppercase tracking-[0.15em] opacity-60 md:mb-1">{title}</p>
                <div className="relative h-6 md:h-8 flex items-center md:block overflow-hidden">
                    <AnimatePresence mode="wait">
                        {!isLoading ? (
                            <motion.p
                                key={String(value)}
                                initial={{ y: 15, opacity: 0 }}
                                animate={{ y: 0, opacity: 1 }}
                                exit={{ y: -15, opacity: 0 }}
                                transition={{ duration: 0.3 }}
                                className="text-lg md:text-2xl font-black tracking-tight tabular-nums absolute md:relative"
                            >
                                {value}
                            </motion.p>
                        ) : (
                            <div className={`w-20 h-5 animate-pulse rounded-md ${isMain ? 'bg-white/20' : 'bg-gray-100'}`} />
                        )}
                    </AnimatePresence>
                </div>
            </div>
            {trend && (
                <div className={`text-[9px] md:text-[10px] font-black px-2 py-1 rounded-lg ${isMain ? 'bg-white/20' : 'bg-emerald-50 text-emerald-600'} absolute top-4 right-4 md:top-6 md:right-6`}>
                    {trend}
                </div>
            )}
        </div>
    );
}
