import { ReactNode } from 'react';

// --- NOWY INTERFEJS DLA WYSZUKIWARKI MIAST ---
export interface CityResult {
  slug: string;
  nazwa: string;
  label: string;
  lat?: number;
  lng?: number;
}

export interface UserProfile {
  name: string
  email: string
  avatar: string
  phone: string
  uid: string
  accountType?: 'private' | 'business'
  bio?: string
  isPremium?: boolean
  premiumExpiresAt?: string
  facebook?: string | null
  instagram?: string | null
  tiktok?: string | null
  website?: string | null
  linkPolecajacy?: string
  liczbaPoleconych?: number
  rekomendacje?: Array<{ tytul: string; opis: string; napisPrzycisku: string; akcja: string }>
  zdjecieTla?: string | null
  imie?: string
  nazwisko?: string
  confidential?: boolean
  ustawionehaslo?: boolean
  /** @deprecated use bio */
  opis?: string
  /** @deprecated use bio */
  biografia?: string
  /** @deprecated use website */
  web?: string
  profilowe?: string
  socialLinks?: { fb?: string; ig?: string; tt?: string; web?: string }
}

export interface Review {
  id: number
  servicePublicId?: string
  /** @deprecated use servicePublicId */
  serviceId?: string | number
  providerUid?: string
  serviceTitle?: string
  userName: string | null
  userAvatar?: string | null
  userUid?: string | null
  imageUrl?: string | null
  rating: number
  text: string | null
  date: string
  autoGenerated?: boolean
  ownerReply?: string | null
  likesCount?: number
}

/**
 * ENTERPRISE LEVEL REFACTOR:
 * ProviderProfile musi być kompatybilny z danymi providera w obiekcie Service.
 * Pola rozszerzone (JoinedDate, Description) są opcjonalne, bo nie ma ich na liście głównej.
 */
export interface ProviderProfile {
  uid: string           // ZAWSZE wymagane w profesjonalnym systemie
  name: string
  avatar: string | null
  responseRate: string
  joinedDate?: string   // Opcjonalne (ładowane w detalu)
  description?: string  // Opcjonalne (ładowane w detalu)
  reviewsCount?: number // Opcjonalne
  rating?: number       // Opcjonalne
  reviews?: Review[]    // Opcjonalne
  is_me?: boolean
  isPremium?: boolean   // Czy wykonawca ma aktywne premium
  isVerified?: boolean  // Czy wykonawca jest zweryfikowany
  deleted?: boolean
  joinedAt?: string | null
  avgRating?: number
  zdjecieTla?: string | null
  servicesCount?: number
  email?: string | null
  telefon?: string | null
  facebook?: string | null
  instagram?: string | null
  tiktok?: string | null
  website?: string | null
  imie?: string | null
  nazwisko?: string | null
  profilowe?: string | null
  joinedYear?: number | null
  city?: string | null
}

export interface Service {
  /** @deprecated use publicId */
  id?: number | string
  publicId?: string
  title: string
  description: string
  price: string
  priceUnit: string
  rating: number
  distance: string

  /** Puste ("") gdy usługa jest zdalna. Używaj isRemoteService() z serviceUtils zamiast sprawdzać bezpośrednio. */
  city: string

  /**
   * Precyzyjne koordynaty geograficzne z API.
   * Mock data: brak (fallback do CITY_COORDS w serviceUtils).
   * API: zawsze obecne dla usług stacjonarnych.
   */
  location?: {
    lat: number;
    lng: number;
  };

  category: string

  /** 0 = usługa pod konkretnym adresem (pin), > 0 = obszar działania (okrąg w km). */
  radius: number

  type: 'offer' | 'request'

  /**
   * Czy usługa jest wykonywana zdalnie/online.
   * Wymagane. Używaj isRemoteService() z serviceUtils jako jedynego źródła prawdy.
   * Przy isRemote: true, city powinno być "".
   */
  isRemote: boolean;

  provider: ProviderProfile

  image: string
  images?: string[]
  videos?: Array<{ url: string; thumbnailUrl?: string | null }>

  /**
   * Czy WYKONAWCA jest teraz aktywny/online.
   * Niezależne od isRemote — wykonawca usługi zdalnej może być offline i odwrotnie.
   * Docelowo: pobierane z API presence w czasie rzeczywistym.
   */
  isOnline: boolean

  deliveryTime: string
  durationMinutes?: number
  bookings: number
  isMine: boolean
  isFavorite?: boolean
  views?: number
  createdAt?: string
  distanceKm?: number | null
  phoneNumber: string
  address?: string
  addressLat?: number
  addressLng?: number
}

export interface Category {
  id: string
  name: string
  icon: ReactNode
  count: number
}

export type BookingStatus = 'pending' | 'accepted' | 'declined' | 'cancelled' | 'completed' | 'reviewed';

export interface BookingData {
  id: string;
  servicePublicId?: string;
  serviceType: 'offer' | 'request';
  serviceTitle: string;
  serviceImage: string;
  providerName: string;
  providerAvatar: string;
  price: string;
  priceUnit: string;
  status: BookingStatus;
  clientReviewed?: boolean;
  createdAt: string;
  // Rezerwacja (offer)
  date?: string;
  time?: string;
  address?: string;
  notes?: string;
  addressLat?: number;
  addressLng?: number;
  // Aplikacja (request)
  message?: string;
  proposedPrice?: string;
  availableFrom?: string;
  // Cykliczne
  seriesId?: string;
  seriesBookings?: Array<{ id: number; date: string; time?: string; status: string }>;
}

export interface ChatMessage {
  id: number
  sender: 'me' | 'other'
  text?: string
  image?: string
  time: string
  bookingData?: BookingData
}

export interface ChatSession {
  servicePublicId?: string
  /** @deprecated use servicePublicId */
  serviceId?: string | number
  serviceTitle: string
  providerName: string
  providerAvatar: string
  lastMessage: string
  timestamp: string
  unread: number
  messages: ChatMessage[]
}

export interface Booking {
  id: number
  servicePublicId: string
  serviceTitle: string
  providerName: string
  providerAvatar: string
  date: string
  address: string
  status: 'confirmed' | 'completed' | 'cancelled'
  price: string
}

export type ToastType = 'success' | 'error' | 'info' | 'warning' | 'custom';

export interface ToastNotification {
  id: number
  type: ToastType // ZMIANA: użyj wspólnego typu
  message: string
  icon?: ReactNode
  className?: string
}

export interface NotificationItem {
  id: number
  title: string
  text: string
  time: string
  read: boolean
  chatId?: string
  type?: string
  senderAvatar?: string | null
  senderName?: string | null
  bookingId?: string | null
  servicePublicId?: string | null
  bookingTab?: string | null
}